### ISSUE TITLE
Missing Import in NAMESPACE and DESCRIPTION

### ISSUE THREAD

**Issue by keblu** [SentometricsResearch/sentometrics.app#9]
Got errors at my first run regarding missing library(tableHTML) and function not recognize : as.data.table.

I guess the code in inst/shiny/ is not checked well by devtools.

**Comment by keblu** [comment]
Specifically, Quanteda, tableHTML, data.table

**Comment by sborms** [comment]
Thanks, these are added! I'll check for similar namespace issues along the way
